name: Post pull request dev

on:
  push:
    branches:
      - develop

env:
  IMAGE_NAME: fast-api
  IMAGE_TAG: latest

concurrency:
  group: ci-deploy-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dev-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} .

      - name: Push Docker image to Docker Hub
        run: |
          docker tag ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} ${{ secrets.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}